migrate(
  (app) => {
    const collections = [
      new Collection({
        name: 'hr_candidates',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'name', type: 'text', required: true },
          { name: 'cargo', type: 'text', required: true },
          { name: 'cv_data', type: 'text' },
          { name: 'match_score', type: 'number' },
          { name: 'status', type: 'text' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
      new Collection({
        name: 'hr_trainings',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'title', type: 'text', required: true },
          { name: 'description', type: 'text' },
          { name: 'category', type: 'text' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
      new Collection({
        name: 'hr_enrollments',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'staff_name', type: 'text', required: true },
          { name: 'training_id', type: 'text', required: true },
          { name: 'status', type: 'text', required: true },
          { name: 'certificate_issued', type: 'bool' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
      new Collection({
        name: 'hr_shifts',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'staff_name', type: 'text', required: true },
          { name: 'sector', type: 'text', required: true },
          { name: 'start_time', type: 'text', required: true },
          { name: 'end_time', type: 'text', required: true },
          { name: 'total_hours', type: 'number' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
      new Collection({
        name: 'it_assets',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'name', type: 'text', required: true },
          { name: 'type', type: 'text', required: true },
          { name: 'serial', type: 'text', required: true },
          { name: 'status', type: 'text', required: true },
          { name: 'last_maintenance', type: 'text' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
      new Collection({
        name: 'it_access_requests',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'user_name', type: 'text', required: true },
          { name: 'system_name', type: 'text', required: true },
          { name: 'status', type: 'text', required: true },
          { name: 'auditor_name', type: 'text' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
      new Collection({
        name: 'iot_sensors',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'name', type: 'text', required: true },
          { name: 'type', type: 'text', required: true },
          { name: 'current_value', type: 'number', required: true },
          { name: 'threshold', type: 'number', required: true },
          { name: 'status', type: 'text', required: true },
          { name: 'unit', type: 'text' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
      new Collection({
        name: 'it_tickets',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'requester_name', type: 'text', required: true },
          { name: 'category', type: 'text', required: true },
          { name: 'description', type: 'text', required: true },
          { name: 'status', type: 'text', required: true },
          { name: 'sla_deadline', type: 'text' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
      new Collection({
        name: 'fb_events',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'title', type: 'text', required: true },
          { name: 'date', type: 'text', required: true },
          { name: 'menu_details', type: 'text' },
          { name: 'price', type: 'number', required: true },
          { name: 'currency', type: 'text', required: true },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
      new Collection({
        name: 'crm_leads',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'name', type: 'text', required: true },
          { name: 'contact', type: 'text', required: true },
          { name: 'score', type: 'number', required: true },
          { name: 'stage', type: 'text', required: true },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
      new Collection({
        name: 'ota_connections',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != ''",
        fields: [
          { name: 'channel_name', type: 'text', required: true },
          { name: 'sync_status', type: 'text', required: true },
          { name: 'last_sync', type: 'text', required: true },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
      }),
    ]

    for (const collection of collections) {
      app.save(collection)
    }
  },
  (app) => {
    const collectionNames = [
      'hr_candidates',
      'hr_trainings',
      'hr_enrollments',
      'hr_shifts',
      'it_assets',
      'it_access_requests',
      'iot_sensors',
      'it_tickets',
      'fb_events',
      'crm_leads',
      'ota_connections',
    ]

    for (const name of collectionNames) {
      try {
        const collection = app.findCollectionByNameOrId(name)
        app.delete(collection)
      } catch (_) {}
    }
  },
)
